
CREATE USER KONG_PG_USER WITH
	LOGIN
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	VALID UNTIL '2099-12-31T23:59:59+08:00' 
    PASSWORD 'KONG_PG_PASSWORD';

CREATE DATABASE kong OWNER KONG_PG_USER;
