# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # so that thanos can recognize a metric was collected by which pm server
  external_labels:
    region: lab
    monitor: fx
    replica: THANOS_REPLICA

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets: [TARGETS_ALERTMANAGER]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - rules/node-alerts-rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: [TARGETS_PROMETHEUS]

  - job_name: 'grafana'
    static_configs:
      - targets: [TARGETS_GRAFANA]

  - job_name: 'node-exporter-static'
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets: [TARGETS_NODE_EXPORTER]

  - job_name: 'node-exporter-consul'
    scrape_interval: 60s
    scrape_timeout: 60s
    consul_sd_configs:
      - server: 192.168.56.11:8500
        scheme: "http"
        tags:
          - prometheus
        # Node metadata key/value pairs to filter nodes for a given service.
        node_meta:
          collector: node

        #[ tag_separator: <string> | default = , ]
        tag_separator: "|"

        # Allow stale Consul results (see https://www.consul.io/api/features/consistency.html). Will reduce load on Consul.
        #[ allow_stale: <boolean> | default = true ]
        allow_stale: true

        # The time after which the provided names are refreshed.
        # On large setup it might be a good idea to increase this value because the catalog will change all the time.
        refresh_interval: 30s

  - job_name: 'node-exporter-file'
    scrape_interval: 60s
    scrape_timeout: 60s
    file_sd_configs:
      # Patterns for files from which target groups are extracted.
      - files:
          - sd_configs/node.yml
        # Refresh interval to re-read the files.
        refresh_interval: 5m

  - job_name: 'pushgateway'
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets: [TARGETS_PUSHGATEWAY]

  - job_name: 'kafka-exporter'
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets:
        - 192.168.56.11:9308
        labels:
          cluster: 'cluster1'

  - job_name: 'kafka-jmx-exporter'
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets:
          - 192.168.56.11:5556
          - 192.168.56.12:5556
        labels:
          cluster: 'cluster1'
